#!/usr/bin/env python3
import rclpy
from rclpy.node import Node
from std_msgs.msg import String
import serial


class UltrasoundNode(Node):
    def __init__(self):
        super().__init__('ultrasound_node')
        # Publisher for ultrasound data
        self.publisher_ = self.create_publisher(String, 'ultrasound_topic', 10)
        # Serial connection to Arduino
        self.serial_port = serial.Serial('/dev/ttyACM0', 9600, timeout=2)
        # Timer: calls callback every 0.1 seconds
        timer_period = 0.1
        self.timer = self.create_timer(timer_period, self.timer_callback)

    def timer_callback(self):
        if self.serial_port.in_waiting > 0:
            # Read line from Arduino
            data_line = self.serial_port.readline().decode('ascii').strip()
            # Create and publish ROS message
            msg = String()
            msg.data = data_line
            self.publisher_.publish(msg)
            # Log published message
            self.get_logger().info(f'Publishing: "{data_line}"')


def main(args=None):
    rclpy.init(args=args)
    ultrasound_node = UltrasoundNode()
    rclpy.spin(ultrasound_node)
    ultrasound_node.destroy_node()
    rclpy.shutdown()


if __name__ == '__main__':
    main()
